name: Build and Push to GHCR

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
         
          tags: ghcr.io/${{ github.repository_owner }}/week3-backend:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./templates/Dockerfile.frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/week3-frontend:latest

  deploy:
    needs: build-and-push
    runs-on: cybersecurity 
    steps:
      - name: Pull and Restart Docker on Desktop
        run: |
          
          cd ~/Desktop/week3/
          docker-compose down
          docker-compose up -d
   
